#macro ASSET_SPRITE spr_assets

#macro ASSET_FRAME_PLAYER_WAND 14
#macro ASSET_FRAME_STAGE_1_MOB 41

#macro ASSET_FRAME_MAP_FIRE 84
#macro ASSET_FRAME_MAP_PALACE 100
#macro ASSET_FRAME_MAP_HUT 101
#macro ASSET_FRAME_MAP_ROOF 103
#macro ASSET_FRAME_MAP_HOUSE 104
#macro ASSET_FRAME_MAP_THREE_TREES 105
#macro ASSET_FRAME_MAP_TREE 107
#macro ASSET_FRAME_MAP_TREE2 108
